import Head from 'next/head';
import Header from '../components/Header/Header';
import CTA from '../components/CTA/CTA';
import Tracker from '../components/Tracker/Tracker';
import About from '../components/About/About';
import Modal from '../components/Modal/Modal';
import { useAppContext } from '../util/ModalContext';

export default function Home() {
    let { state, setSelection } = useAppContext();
    let { selection, completion } = state;
    return (
        <div className={selection || completion ? 'overlay' : ''}>
            <Head>
                <title>Frontend Mentor | Crowdfunding product page</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link
                    rel='icon'
                    type='image/png'
                    sizes='32x32'
                    href='./images/favicon-32x32.png'
                />
            </Head>
            <Header />
            <CTA />
            <Tracker />
            <About />
            <Modal />
        </div>
    );
}
